version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: weekly
    groups:
      client:
        patterns: ["*"]
  - package-ecosystem: gomod
    directory: /server
    schedule:
      interval: weekly
    groups:
      server:
        patterns: ["*"]
